  version: '3'
  services:
    db:
      # Official Postgres image from DockerHub (we use the last version)
      image: 'postgres:latest'
      ports:
        - "127.0.0.1:5432:5432"
      environment:
        POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
        POSTGRES_PASSWORD: postgres # The PostgreSQL password (useful to connect to the database)
        POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at first launch)
        POSTGRES_HOST_AUTH_METHOD: trust
      volumes:
        - /home/ec2-user/db:/var/lib/postgresql/data/
#        - ./sql:/docker-entrypoint-initdb.d/
      # volumes:
      #   - /home/ec2-user/db:/var/lib/postgresql/data/
      restart: 'always'
      logging:
        driver: "json-file"
        options:
          max-size: "10k"
          max-file: "3"
    nginx:
      image: nginx
      ports:
        - "80:80"
        - "443:443"
      restart: 'always'
      logging:
        driver: "json-file"
        options:
          max-size: "10k"
          max-file: "3"
      volumes:
        - /home/ec2-user/teamai55-22.bham.team/teamai55-22.bham.team:/key
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    tpdjango:
      image: git.cs.bham.ac.uk:5050/team-projects-2022-23/team22-22:tpdjango
#      ports:
#         - "8000:8000"
      restart: 'always'
      logging:
        driver: "json-file"
        options:
          max-size: "10k"
          max-file: "3"
    tpvue:
      image:  git.cs.bham.ac.uk:5050/team-projects-2022-23/team22-22:tpvue
      restart: 'always'
      logging:
        driver: "json-file"
        options:
          max-size: "10k"
          max-file: "3"

  # - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker run -d -p 8000:8000 --name tpdjango --network tpnetwork --network-alias tpdjango ${CI_REGISTRY_IMAGE}:tpdjango"

  # - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker run -d -p 8000:8000 --name tpdjango --network tpnetwork --network-alias tpdjango ${CI_REGISTRY_IMAGE}:tpdjango"
  # - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker run -d -p 80:80 --name tpnginx --network tpnetwork --network-alias tpnginx ${CI_REGISTRY_IMAGE}:tpnginx"

